#!/usr/bin/env bash
# NeuroVLA — Jetson Thor 环境安装 + 模型下载 + 部署准备
# 推荐在 vla_docker_env 容器内运行（已含 sm_110 PyTorch + flash-attn）
#
# 用法（宿主机）:
#   bash NeuroVLA/scripts/setup_thor_deploy.sh
#
# 用法（已在容器内）:
#   bash /workspace/NeuroVLA/scripts/setup_thor_deploy.sh --in-container

set -euo pipefail

IN_CONTAINER=false
SKIP_DOWNLOAD=false
for arg in "$@"; do
  case "$arg" in
    --in-container) IN_CONTAINER=true ;;
    --skip-download) SKIP_DOWNLOAD=true ;;
  esac
done

REPO_ROOT="/workspace/NeuroVLA"
VENV_DIR="${REPO_ROOT}/.venv-neurovla"
MODEL_ROOT="${NEUROVLA_MODEL_ROOT:-/data/checkpoints/neurovla}"
QWEN_DIR="${MODEL_ROOT}/Qwen2.5-VL-3B-Instruct"
CKPT_REPO="AlphaBrainGroup/neurovla-cl-libero-goal"
CKPT_RUN_DIR="${MODEL_ROOT}/neurovla-cl-libero-goal"
CKPT_DIR="${CKPT_RUN_DIR}/checkpoints"
CKPT_PT="${CKPT_DIR}/task_9_id9_steps_100000_pytorch_model.pt"

run() {
  if [[ "${IN_CONTAINER}" == "true" ]]; then
    bash -lc "$*"
  else
    docker exec vla_docker_env bash -lc "$*"
  fi
}

echo "=== NeuroVLA Thor Setup ==="
echo "REPO_ROOT=${REPO_ROOT}"
echo "VENV=${VENV_DIR}"
echo "MODEL_ROOT=${MODEL_ROOT}"

# --- 1. venv（继承容器内 Jetson PyTorch）---
run "
set -e
cd ${REPO_ROOT}
if [[ ! -d ${VENV_DIR} ]]; then
  python3 -m venv --system-site-packages ${VENV_DIR}
fi
source ${VENV_DIR}/bin/activate
python -c \"import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available(), torch.cuda.get_device_name(0)); print('cap', torch.cuda.get_device_capability(0))\"
pip install -U pip wheel
# 推理最小依赖（跳过 deepspeed / pytorch3d 等训练专用包）
pip install 'transformers>=4.57.0,<4.58' accelerate omegaconf qwen-vl-utils einops scipy pillow
pip install pydantic pyarrow websocket-client websockets msgpack numpy
pip install snntorch
pip install huggingface_hub
"

# --- 2. 修复 playground 断链 ---
run "
mkdir -p /data/checkpoints
mkdir -p ${MODEL_ROOT}
if [[ -L ${REPO_ROOT}/playground/Pretrained_models ]]; then
  rm -f ${REPO_ROOT}/playground/Pretrained_models
fi
ln -sfn ${MODEL_ROOT} ${REPO_ROOT}/playground/Pretrained_models
"

# --- 3. 下载 Qwen + Checkpoint ---
if [[ "${SKIP_DOWNLOAD}" == "false" ]]; then
  run "
set -e
source ${VENV_DIR}/bin/activate
export HF_HOME=\${HF_HOME:-/data/cache/huggingface}
export HF_ENDPOINT=\${HF_ENDPOINT:-https://hf-mirror.com}
export HF_HUB_DOWNLOAD_TIMEOUT=\${HF_HUB_DOWNLOAD_TIMEOUT:-300}
mkdir -p \${HF_HOME} ${MODEL_ROOT}

if [[ ! -f ${QWEN_DIR}/model-00001-of-00002.safetensors ]]; then
  echo '>>> Downloading Qwen2.5-VL-3B-Instruct via' \${HF_ENDPOINT}
  hf download Qwen/Qwen2.5-VL-3B-Instruct \\
    --local-dir ${QWEN_DIR} \\
    --max-workers 4
else
  echo '>>> Qwen already exists: ${QWEN_DIR}'
fi

mkdir -p ${CKPT_DIR}
if [[ ! -f ${CKPT_PT} ]]; then
  echo '>>> Downloading NeuroVLA checkpoint (${CKPT_REPO}) ...'
  TMP_DIR=\$(mktemp -d)
  hf download ${CKPT_REPO} --local-dir \${TMP_DIR}
  # 重组为 read_mode_config 期望的结构: <run_dir>/config.yaml + checkpoints/*.pt
  mkdir -p ${CKPT_RUN_DIR}/checkpoints
  cp -f \${TMP_DIR}/config.yaml ${CKPT_RUN_DIR}/config.yaml
  cp -f \${TMP_DIR}/dataset_statistics.json ${CKPT_RUN_DIR}/dataset_statistics.json
  cp -f \${TMP_DIR}/task_9_id9_steps_100000_pytorch_model.pt ${CKPT_PT}
  rm -rf \${TMP_DIR}
else
  echo '>>> Checkpoint already exists: ${CKPT_PT}'
fi

# 修补 config：本地 Qwen 路径 + SDPA（与 AlphaBrain 发布 checkpoint 一致）
python3 - <<'PY'
from pathlib import Path
import yaml

run_dir = Path("${CKPT_RUN_DIR}")
cfg_path = run_dir / "config.yaml"
if cfg_path.exists():
    cfg = yaml.safe_load(cfg_path.read_text())
    fw = cfg.setdefault("framework", {})
    qw = fw.setdefault("qwenvl", {})
    qw["base_vlm"] = "${QWEN_DIR}"
    qw["attn_implementation"] = "sdpa"
    cfg_path.write_text(yaml.dump(cfg, default_flow_style=False, allow_unicode=True))
    print("Patched config.yaml:", cfg_path)
PY
"
else
  echo ">>> Skipping model download (--skip-download)"
fi

# --- 4. 写入部署 env 文件 ---
ENV_FILE="${REPO_ROOT}/scripts/thor_deploy.env"
run "
cat > ${ENV_FILE} <<EOF
# Auto-generated by setup_thor_deploy.sh
export NEUROVLA_REPO=${REPO_ROOT}
export NEUROVLA_VENV=${VENV_DIR}
export NEUROVLA_MODEL_ROOT=${MODEL_ROOT}
export NEUROVLA_QWEN_PATH=${QWEN_DIR}
export NEUROVLA_CKPT_PATH=${CKPT_PT}
export PYTHONPATH=${REPO_ROOT}:\${PYTHONPATH:-}
export HF_HOME=\${HF_HOME:-/data/cache/huggingface}
EOF
echo '>>> Wrote' ${ENV_FILE}
"

echo ""
echo "=== Setup complete ==="
echo "Next: bash NeuroVLA/scripts/run_thor_server.sh"
